AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to create a single S3 bucket with folders for Bronze, Silver, Gold, Athena Results, and Scripts stages in a Data Lake, and AWS Glue resources for data ingestion and ETL jobs, and Athena setup"

Resources:
  DataLakeBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: "data-lake-demo"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  GlueDatabase:
    Type: "AWS::Glue::Database"
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      DatabaseInput:
        Name: "data_lake_db"
        Description: "Glue database for the data lake"

  GlueETLJobIngestJasmin:
    Type: "AWS::Glue::Job"
    Properties:
      Name: "data_lake_jasmin_etl_job_ingest"
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://data-lake-demo/scripts/etl_api_jasmin.py"
        PythonVersion: "3"
      GlueVersion: "3.0"
      DefaultArguments:
        "--TempDir": !Sub "s3://data-lake-demo/temp/"
        "--job-bookmark-option": "job-bookmark-enable"
        "--enable-metrics": ""
      MaxRetries: 1
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Timeout: 2880

  GlueETLJobIngestStreamateMock:
    Type: "AWS::Glue::Job"
    Properties:
      Name: "data_lake_streamate_mock_etl_job_ingest"
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://data-lake-demo/scripts/etl_api_streamate_mock.py"
        PythonVersion: "3"
      GlueVersion: "3.0"
      DefaultArguments:
        "--TempDir": !Sub "s3://data-lake-demo/temp/"
        "--job-bookmark-option": "job-bookmark-enable"
        "--enable-metrics": ""
      MaxRetries: 1
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Timeout: 2880

  GlueETLJobMongoDB:
    Type: "AWS::Glue::Job"
    Properties:
      Name: "data_lake_mongodb_etl_job"
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://data-lake-demo/scripts/etl_mongo_collections.py"
        PythonVersion: "3"
      GlueVersion: "3.0"
      DefaultArguments:
        "--TempDir": !Sub "s3://data-lake-demo/temp/"
        "--job-bookmark-option": "job-bookmark-enable"
        "--enable-metrics": ""
      MaxRetries: 1
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Timeout: 2880
      Connections:
        Connections:
          - !Ref GlueJobConnection

  GlueETLJobIngestMongoDBOffices:
    Type: "AWS::Glue::Job"
    Properties:
      Name: "data_lake_mongodb_offices_etl_job_ingest"
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://data-lake-demo/scripts/etl_mongo_offices.py"
        PythonVersion: "3"
      GlueVersion: "3.0"
      DefaultArguments:
        "--TempDir": !Sub "s3://data-lake-demo/temp/"
        "--job-bookmark-option": "job-bookmark-enable"
        "--enable-metrics": ""
      MaxRetries: 1
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Timeout: 2880
      Connections:
        Connections:
          - !Ref GlueJobConnection

  GlueETLJobIngestMongoDBCities:
    Type: "AWS::Glue::Job"
    Properties:
      Name: "data_lake_mongodb_cities_etl_job_ingest"
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://data-lake-demo/scripts/etl_mongo_cities.py"
        PythonVersion: "3"
      GlueVersion: "3.0"
      DefaultArguments:
        "--TempDir": !Sub "s3://data-lake-demo/temp/"
        "--job-bookmark-option": "job-bookmark-enable"
        "--enable-metrics": ""
      MaxRetries: 1
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Timeout: 2880
      Connections:
        Connections:
          - !Ref GlueJobConnection

  GlueETLJobIngestMongoDBRooms:
    Type: "AWS::Glue::Job"
    Properties:
      Name: "data_lake_mongodb_rooms_etl_job_ingest"
      Role: !GetAtt GlueServiceRole.Arn
      Command:
        Name: "glueetl"
        ScriptLocation: !Sub "s3://data-lake-demo/scripts/etl_mongo_rooms.py"
        PythonVersion: "3"
      GlueVersion: "3.0"
      DefaultArguments:
        "--TempDir": !Sub "s3://data-lake-demo/temp/"
        "--job-bookmark-option": "job-bookmark-enable"
        "--enable-metrics": ""
      MaxRetries: 1
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Timeout: 2880
      Connections:
        Connections:
          - !Ref GlueJobConnection

  GlueServiceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "glue.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "GlueServicePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:ListBucket"
                Resource:
                  - !Sub "arn:aws:s3:::data-lake-demo/*"
              - Effect: "Allow"
                Action:
                  - "glue:*"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "tag:GetResources"
                  - "tag:TagResources"
                  - "tag:UntagResources"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "iam:CreateRole"
                  - "iam:DeleteRole"
                  - "iam:AttachRolePolicy"
                  - "iam:DetachRolePolicy"
                  - "iam:PassRole"
                  - "iam:PutRolePolicy"
                  - "iam:GetRole"
                Resource: "arn:aws:iam::*:role/DataLake-GlueServiceRole-*"
              - Effect: "Allow"
                Action:
                  - "athena:CreateWorkGroup"
                  - "athena:GetWorkGroup"
                  - "athena:UpdateWorkGroup"
                  - "athena:DeleteWorkGroup"
                  - "athena:ListWorkGroups"
                Resource: "*"
              - Effect: "Allow"
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource: "*"

  GlueJobConnection:
    Type: "AWS::Glue::Connection"
    Properties:
      CatalogId: !Ref "AWS::AccountId"
      ConnectionInput:
        Name: "MongoDBConnection"
        ConnectionType: "NETWORK"
        PhysicalConnectionRequirements:
          AvailabilityZone: "us-east-1a"
          SecurityGroupIdList:
            - sg-0008fd71a9b867731
          SubnetId: "subnet-0d005ef0bb1b57797"

  CharactersBronzeCrawler:
    Type: "AWS::Glue::Crawler"
    Properties:
      Name: "ingest_bronze_characters"
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: "data_lake_db"
      Targets:
        S3Targets:
          - Path: "s3://data-lake-demo/bronze/characters/"

  StreamateMockBronzeCrawler:
    Type: "AWS::Glue::Crawler"
    Properties:
      Name: "ingest_bronze_streamate_mock"
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: "data_lake_db"
      Targets:
        S3Targets:
          - Path: "s3://data-lake-demo/bronze/streamate_mock/"

  DBUsersBronzeCrawler:
    Type: "AWS::Glue::Crawler"
    Properties:
      Name: "ingest_bronze_db_users"
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: "data_lake_db"
      Targets:
        S3Targets:
          - Path: "s3://data-lake-demo/bronze/dbUsers/"

  DBOfficesBronzeCrawler:
    Type: "AWS::Glue::Crawler"
    Properties:
      Name: "ingest_bronze_db_offices"
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: "data_lake_db"
      Targets:
        S3Targets:
          - Path: "s3://data-lake-demo/bronze/dbOffices/"

  DBCitiesBronzeCrawler:
    Type: "AWS::Glue::Crawler"
    Properties:
      Name: "ingest_bronze_db_cities"
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: "data_lake_db"
      Targets:
        S3Targets:
          - Path: "s3://data-lake-demo/bronze/dbCities/"

  DBRoomsBronzeCrawler:
    Type: "AWS::Glue::Crawler"
    Properties:
      Name: "ingest_bronze_db_rooms"
      Role: !GetAtt GlueServiceRole.Arn
      DatabaseName: "data_lake_db"
      Targets:
        S3Targets:
          - Path: "s3://data-lake-demo/bronze/dbRooms/"

  AthenaWorkGroup:
    Type: "AWS::Athena::WorkGroup"
    Properties:
      Name: "data-lake-workgroup"
      State: "ENABLED"
      Description: "Work group for Data Lake queries"
      WorkGroupConfiguration:
        BytesScannedCutoffPerQuery: 1000000000
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true
        RequesterPaysEnabled: false
        ResultConfiguration:
          OutputLocation: "s3://data-lake-demo/athena-results/"

  CreateS3FoldersFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "index.handler"
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import boto3
          import cfnresponse

          def handler(event, context):
              s3 = boto3.client('s3')
              bucket = event['ResourceProperties']['BucketName']
              prefixes = event['ResourceProperties']['Prefixes']
              for prefix in prefixes:
                  s3.put_object(Bucket=bucket, Key=prefix)
              cfnresponse.send(event, context, cfnresponse.SUCCESS, {})

      Runtime: "python3.8"
      Timeout: 60

  CreateS3FoldersCustomResource:
    Type: "Custom::CreateS3Folders"
    Properties:
      ServiceToken: !GetAtt CreateS3FoldersFunction.Arn
      BucketName: !Ref DataLakeBucket
      Prefixes:
        - "bronze/"
        - "silver/"
        - "gold/"
        - "athena-results/"
        - "scripts/"

  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaS3AccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "s3:PutObject"
                Resource: !Sub "arn:aws:s3:::data-lake-demo/*"

Outputs:
  DataLakeBucketName:
    Description: "Name of the Data Lake S3 bucket"
    Value: !Ref DataLakeBucket

  GlueDatabaseName:
    Description: "Name of the Glue database"
    Value: !Ref GlueDatabase

  GlueETLJobJasminIngestName:
    Description: "Name of the Glue ETL job for ingesting data from Jasmin API"
    Value: !Ref GlueETLJobIngestJasmin

  GlueETLJobIngestStreamateMockName:
    Description: "Name of the Glue ETL job for ingesting data from Streamate API (mock)"
    Value: !Ref GlueETLJobIngestStreamateMock

  GlueETLJobMongoDBIngestName:
    Description: "Name of the Glue ETL job for ingesting data from MongoDB (users)"
    Value: !Ref GlueETLJobMongoDB

  GlueETLJobIngestMongoDBOfficesName:
    Description: "Name of the Glue ETL job for ingesting data from MongoDB (offices)"
    Value: !Ref GlueETLJobIngestMongoDBOffices

  GlueETLJobIngestMongoDBCitiesName:
    Description: "Name of the Glue ETL job for ingesting data from MongoDB (cities)"
    Value: !Ref GlueETLJobIngestMongoDBOffices

  GlueETLJobIngestMongoDBRoomsName:
    Description: "Name of the Glue ETL job for ingesting data from MongoDB (rooms)"
    Value: !Ref GlueETLJobIngestMongoDBRooms

  CharactersBronzeCrawlerName:
    Description: "Name of the Glue Crawler for the Bronze data (characters)"
    Value: !Ref CharactersBronzeCrawler

  StreamateMockBronzeCrawlerName:
    Description: "Name of the Glue Crawler for the Bronze data (Streamate Mock)"
    Value: !Ref StreamateMockBronzeCrawler

  DBUsersBronzeCrawlerName:
    Description: "Name of the Glue Crawler for the Bronze data (DB Users)"
    Value: !Ref DBUsersBronzeCrawler

  DBOfficesBronzeCrawlerName:
    Description: "Name of the Glue Crawler for the Bronze data (DB Offices)"
    Value: !Ref DBOfficesBronzeCrawler

  DBCitiesBronzeCrawlerName:
    Description: "Name of the Glue Crawler for the Bronze data (DB Cities)"
    Value: !Ref DBCitiesBronzeCrawler

  DBRoomsBronzeCrawlerName:
    Description: "Name of the Glue Crawler for the Bronze data (DB Rooms)"
    Value: !Ref DBRoomsBronzeCrawler

  AthenaWorkGroupName:
    Description: "Name of the Athena work group"
    Value: !Ref AthenaWorkGroup
